### PR TITLE
Web3 1.x

### LINKED ISSUE #16: Move to web3.js 1.x

### PR DESCRIPTION
**Pull request by axic**
Fixes #16.

### CODE REVIEW

**Comment by axic** [comment]
This works with geth, but should npm release web3-extended first before merging this.

**Comment by jwasinger** [comment]
@axic I recall you saying the changes here were merged upstream into Web3.  Is that correct or is this PR still necessary?

**Comment by axic** [comment]
> I recall you saying the changes here were merged upstream into Web3. Is that correct or is this PR still necessary?

Hm? This PR changes etherchain from using web3 0.x to web3 1.x.

**Comment by axic** [comment]
Ah right, some of the debug methods were merged upstream, but no web3 1.x beta release has been made with them.

I'm in contact with the new maintainer to figure out the best way, but so far this PR is needed if we want to use web3 1.x.

I think we should, but if we do we better make that decision right now and not in 3 weeks time to give us enough time for testing.

**Comment by jwasinger** [comment]
Okay, Still configuring the staging environment with terraform but then I will test this.

**Review by jwasinger — APPROVED** [review]

**Pull request merged**
