### PR TITLE
add account names

### LINKED ISSUE #30: Name known accounts
Also could add the following to `this.names`:
```
    "0xefadf166849f06eee4b44ddb78e4162580f436b1": "ewasm Faucet",
    "0x031159df845ade415202e6da299223cb640b9db0": "ewasm miner1"
```

Though it only shows up on the blocks page and not on the accounts page.

Could also name sentinel, evm2wasm, etc.

### PR DESCRIPTION
**Pull request by hugo-dc**
Closes #30.

It shows the account name in the accounts page, block page, etc.

### CODE REVIEW

**Comment by jwasinger** [comment]
I think we should make this configurable instead of hardcoding.  E.g. see what I have done with rpcEndpoint here: https://github.com/ewasm/etherchain-light/pull/35 .

Then we generate config during deployment like this: 
https://github.com/ethereum/cluster/blob/master/ewasm-testnet/azure/ansible/roles/faucet/tasks/main.yaml#L29-L33

**Review by jwasinger — DISMISSED** [review]
I think we should make this configurable instead of hardcoding. 


E.g. see what I have done with `rpcEndpoint` here: #35 .  Then we generate config during deployment like this:https://github.com/ethereum/cluster/blob/master/ewasm-testnet/azure/ansible/roles/faucet/tasks/main.yaml#L29-L33

**Comment by hugo-dc** [comment]
@jwasinger what would be better? to add this accounts to the template and the config example files?, or should I create a new file which contains the account address/names and then be read by the config.py script?

**Comment by axic** [comment]
I think we should include this for now in the testnet.

**Comment by cdetrio** [comment]
The configurable rpc endpoint was already fixed, btw.

**Pull request merged**
