### PR TITLE
change submit transaction, to send transactions as in ewasm-studio

### LINKED ISSUE #22: Add "send transaction"
Just like https://github.com/ewasm/ewasm-studio

Currently only "send raw transaction" is supported, but should also be possible to support this with injected web3.

### PR DESCRIPTION
**Pull request by hugo-dc**
Previous `Submit transaction` functionality only accepted an already signed transaction, now it is using metamask to create a new transaction as is done in ewasm-studio.

Part of #12. Closes #22.

### CODE REVIEW

**Comment by jwasinger** [comment]
@hugo-dc does this work for you with Geth?

**Comment by hugo-dc** [comment]
@jwasinger didn't try with geth, I will take a look

**Comment by axic** [comment]
Is it possible to keep both options? Two different tabs: submit raw transaction, submit transaction with metamask.

**Comment by hugo-dc** [comment]
@jwasinger it is not working with geth, here is the current error:

```
Error: [ethjs-rpc] rpc error with payload {"id":7555495060964,"jsonrpc":"2.0","params":["0xf86680843b9aca00825208947338954a68f72e8a53d43a6835ee45cd5f014c76830f42408026a06539c210c59d609f1192d72b3423b2e657a23434c4545b2801af7dc1345bd50aa0608e02cab3e51575657a290b122cd0c95c110222c3fc648d6a616a3bbdd12952"],"method":"eth_sendRawTransaction"} Error: invalid sender
```

will continue checking

@axic it is a good idea to keep both, I will do that when I find out what's the current problem with geth

**Comment by hugo-dc** [comment]
@jwasinger it is working with geth.
@axic added the send raw transaction feature back.

**Comment by jwasinger** [comment]
@hugo-dc we made some changes to the endpoint format (https://github.com/ewasm/etherchain-light/commit/916e318d57d4fba545641bf2f85c953838cc4572) can you modify this PR to be compatible?

**Comment by hugo-dc** [comment]
@jwasinger I updated this PR to make it compatible with previous changes.

**Comment by axic** [comment]
Can we rebase and merge this?

**Comment by hugo-dc** [comment]
rebased

**Comment by cdetrio** [comment]
This only has the "send transaction" part of ewasm-studio.  The "Contract Creation" part, which lets the user paste wast code to deploy a wasm contract, is not yet implemented.

**Comment by cdetrio** [comment]
This is broken at the moment, returns `Uncaught Error: invalid address`.  Might be related to this warning which also appears in the js console:

```
inpage.js:1 ATTENTION: In an effort to improve user privacy, MetaMask stopped exposing user accounts to dapps if "privacy mode" is enabled on November 2nd, 2018. Dapps should now call provider.enable() in order to view and use accounts. Please see https://bit.ly/2QQHXvF for complete information and up-to-date example code.
```

**Comment by hugo-dc** [comment]
rebased, and fixed redirection url

**Review by cdetrio — APPROVED** [review]

**Pull request merged**
