### PR TITLE
Add faucet to etherchain-light

### LINKED ISSUE #31: Add faucet support to etherchain light

### PR DESCRIPTION
**Pull request by hugo-dc**
Closes #31.

I added the faucet address to the  `config.js` file, you can add the private key there as well, but I'm not sure if that's a good idea, any thoughts?

### CODE REVIEW

**Comment by axic** [comment]
Can we rebase and merge this?

**Comment by hugo-dc** [comment]
rebased

**Comment by cdetrio** [comment]
This doesn't have IP-based rate limiting like the original faucet, is that okay?  https://github.com/ewasm/eth-faucet/blob/master/server.js#L75-L79

Also, it will need the config.py script to inject the private key:  https://github.com/ewasm/eth-faucet/blob/master/config.py

**Comment by hugo-dc** [comment]
@cdetrio I added the IP-based limit, changed the config.py script to inject the private key and also removed unused rpcEndpoint parameter, these changes also considers metamask with privacy option enabled. This branch has been updated with the latest changes in `ewasm`

**Comment by hugo-dc** [comment]
Depends on https://github.com/ewasm/etherchain-light/pull/74 , I want to use the same `utils.js` file which was pushed in that PR

**Review by jwasinger — APPROVED** [review]

**Pull request merged**
